<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Attribute.fs" />
    <Compile Include="TestType.fs" />
    <Compile Include="TestPatterns.fs" />
    <Compile Include="TestRecord.fs" />
    <Compile Include="TestUnion.fs" />
    <Compile Include="TestSurface.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ApiSurface" Version="5.0.8" />
    <PackageReference Include="FsUnit" Version="7.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShapeSifter\ShapeSifter.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="CsvExample\CsvParser.fs" />
    <Compile Include="CsvExample\TestCsvParser.fs" />
    <EmbeddedResource Include="CsvExample\TestData.csv" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="TestExamples.fs" />
  </ItemGroup>

</Project>
